100 creating a toast on the channels
CruSea/soul-sync-frontend pull request #101
Opened 2024-12-23 07:13 UTC by EyosiSol

- a toast appears when a channel is added successfully and deleted successfully

2024-12-24 22:44 UTC, misudesu commented
reduce file change number  in PR,  you are good here!  but try more. work in specific and send separately

2024-12-24 22:47 UTC, misudesu approved these changes

2024-12-26 09:21 UTC, misudesu requested changes
check the conflict?

2024-12-26 12:00 UTC, EyosiSol commented
channel deleted toast 

![image](https://github.com/user-attachments/assets/ba5220d7-a195-4675-a470-7aaf35acf988)

2024-12-26 12:01 UTC, misudesu approved these changes

2024-12-26 12:11 UTC, merged