82 update the channels page for the admin
CruSea/soul-sync-frontend pull request #88
Opened 2024-12-13 07:19 UTC by EyosiSol

- Created Date as A parameter was added 
- Searching and Filtering was added 
- Icon's automatically added based on the channel type 
- container hieght issues were fixed

2024-12-24 20:22 UTC, misudesu commented
attach final image please!

2024-12-24 21:15 UTC, misudesu requested changes

2024-12-24 21:15 UTC, misudesu commented on components/shared/invite-admin-dialog.tsx
> +    <Dialog open={isOpen} onOpenChange={setIsOpen}>
this is what i recommend you , reuse it

2024-12-24 21:15 UTC, misudesu commented on components/shared/layout/sidebar.tsx
>  const menuItems = [
make it separate the menu and import it. we can manage this from one place. we have to do it, as easy to access

2024-12-24 21:15 UTC, misudesu commented on components/shared/mentors.tsx
>  "use client";
👍awesome it is good to use as SSR

2024-12-26 07:57 UTC, EyosiSol commented
![image](https://github.com/user-attachments/assets/bf9bac2d-c893-4db6-8689-07dfed03211e)

2024-12-26 08:54 UTC, EyosiSol commented
![image](https://github.com/user-attachments/assets/5960b233-c442-4f40-b710-ff1eb238458e)

2024-12-26 09:17 UTC, misudesu approved these changes

2024-12-26 09:18 UTC, merged